"""Add user_type_id to admin_users

Revision ID: 81df35e92e9a
Revises: 5e8456131eaf
Create Date: 2026-01-12 11:30:34.361607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81df35e92e9a'
down_revision = '5e8456131eaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_type_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user_type', ['user_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_type_id')

    # ### end Alembic commands ###
